### ISSUE TITLE
No video in the composition using Avermedia Capture Card with static image and Multipresença

### ISSUE THREAD

**Issue by germanocaumo** [mconf/bbb-webrtc-sfu#104] opened 2019-08-16 13:56 UTC
Using Multipresença to call _redacted server_ with camera Avermedia U3 sometimes the video is not shown in the composition (all black), but it is OK in the web.
It seems related to keyframes, tried to reduce gop in the encoder and then it works.

**Comment by mariogasparoni** [comment] 2019-08-19 16:20
Possible duplicate of https://github.com/mconf/kms-core/issues/18

**Comment by prlanzarin** [comment] 2020-03-06 02:14
Closing this in favour of https://github.com/mconf/kms-core/issues/18 @mgasp @germanocaumo

**Closed by prlanzarin** 2020-03-06 02:14 UTC
Labels: bug
